from __future__ import annotations

# uopcParallelAxis_t
AXIS_UNKNOWN = 0
AXIS_DP = 1
AXIS_FSDP = 2
AXIS_ZERO = 3
AXIS_TP = 4
AXIS_PP = 5
AXIS_CP = 6
AXIS_EP = 7

# uopcPhase_t
PHASE_UNKNOWN = 0
PHASE_FORWARD = 1
PHASE_PRE_BACKWARD = 2
PHASE_POST_BACKWARD = 3
PHASE_OPTIMIZER = 4
PHASE_P2P_BOUNDARY = 5

# uopcProcessGroupKind_t
PG_UNKNOWN = 0
PG_DP_REPLICA = 1
PG_DP_SHARD = 2
PG_TP = 3
PG_EP = 4
PG_CP = 5
PG_PP = 6

# uopcOverlapWindowType_t
WINDOW_UNKNOWN = 0
WINDOW_BACKWARD_AR_VS_NEXT_GEMM = 1
WINDOW_BACKWARD_RS_VS_NEXT_GRAD = 2
WINDOW_FORWARD_AG_VS_CURRENT_GEMM = 3
WINDOW_BACKWARD_PREFETCH_AG_VS_CURRENT_GRAD = 4
WINDOW_A2A_VS_EXPERT_GEMM = 5
WINDOW_P2P_VS_PIPELINE_GEMM = 6
